export const BANARS_DATA = [
  {
    title: "من هو عبدالرحمن",
    buttonText: "اكتشف المزيد",
    buttonLink: "./about",
    textColor: "light",
    description: "",
    bannerUrl: "/slide_img_1.jpg",
    srcType: "image",
  },
  {
    title: "توقيع اتفاقية اطلاق اول برنامج #حياة_الطفل في المملكة العربية",
    buttonText: "آخر الأخبار",
    buttonLink: "./media",
    description: "",
    textColor: "light",
    bannerUrl: "./video_cover.mp4",
    srcType: "video",
  },
  {
    title: "أهلا بشهر التوعية بتخصص حياة الطفل",
    buttonText: "اكتشف المزيد",
    buttonLink: "./child-life",
    description: "",
    textColor: "dark",
    bannerUrl: "/slide_img_2.jpg",
    srcType: "image",
  },
  {
    title: `ما هو تخصص حياة الطفل؟`,
    buttonText: "اكتشف فعالياتنا",
    buttonLink: "#calender",
    description: "",
    textColor: "light",
    bannerUrl: "/slide_img_3.jpg",
    srcType: "image",
  },
];
