export const whoDataAR = {
  BANARS_DATA: [
    {
      title: "من هو عبدالرحمن",
      buttonText: "اكتشف المزيد",
      buttonLink: "./about",
      textColor: "light",
      description: "",
      bannerUrl: "/slide_img_1.jpg",
      srcType: "image",
    },
    {
      title: "توقيع اتفاقية اطلاق اول برنامج #حياة_الطفل في المملكة العربية",
      buttonText: "آخر الأخبار",
      buttonLink: "./media",
      description: "",
      textColor: "light",
      bannerUrl: "./video_cover.mp4",
      srcType: "video",
    },
    {
      title: "أهلا بشهر التوعية بتخصص حياة الطفل",
      buttonText: "اكتشف المزيد",
      buttonLink: "./child-life",
      description: "",
      textColor: "dark",
      bannerUrl: "/slide_img_2.jpg",
      srcType: "image",
    },
    {
      title: `ما هو تخصص حياة الطفل؟`,
      buttonText: "اكتشف فعالياتنا",
      buttonLink: "#calender",
      description: "",
      textColor: "light",
      bannerUrl: "/slide_img_3.jpg",
      srcType: "image",
    },
  ],
};
export const whoDataEN = {
  BANARS_DATA: [
    {
      title: "Who is Abdulrahman",
      buttonText: "Find out more",
      buttonLink: "./about",
      textColor: "light",
      description: "",
      bannerUrl: "/slide_img_1.jpg",
      srcType: "image",
    },
    {
      title:
        "Signing an agreement to launch the first #ChildLife program in the Kingdom of Saudi Arabia",
      buttonText: "Latest news",
      buttonLink: "./media",
      description: "",
      textColor: "light",
      bannerUrl: "./video_cover.mp4",
      srcType: "video",
    },
    {
      title: "Welcome to Child Life Awareness Month",
      buttonText: "Find out more",
      buttonLink: "./child-life",
      description: "",
      textColor: "dark",
      bannerUrl: "/slide_img_2.jpg",
      srcType: "image",
    },
    {
      title: "What is a child life major?",
      buttonText: "Discover our events",
      buttonLink: "#calender",
      description: "",
      textColor: "light",
      bannerUrl: "/slide_img_3.jpg",
      srcType: "image",
    },
  ],
};
