export const whoDataAR = {
  BANARS_DATA: [
    {
      title: "من هو \n عبدالرحمن؟",
      buttonText: "المزيد",
      buttonLink: "./about#story",
      buttonTarget: "_self",
      textColor: "light",
      description: "",
      bannerUrl: "/slide_img_1.jpg",
      bannerUrl_mob: "/slide_img_1_mob.jpg",
      srcType: "image",
    },
    {
      title:
        "توقيع اتفاقية اطلاق اول برنامج #حياة_الطفل في المملكة العربية السعودية",
      buttonText: "المزيد",
      buttonLink: "https://youtu.be/H1WqNYnCyRA",
      buttonTarget: "_blank",
      description:
        "تم بحمدالله اطلاق اول برنامج حياة طفل في المملكة العربية السعودية بالتعاون مع جمعية سند الخيرية ومدينة الملك فهد الطبية وسيباشر اخصائيات حياة الطفل مهامهم في منتصف شهر مارس .. سعداء بهذا الانجاز !",
      textColor: "light",
      bannerUrl: "./video_cover.mp4",
      srcType: "video",
    },
    {
      title: "أهلا بشهر التوعية\n بتخصص حياة الطفل",
      buttonText: "المزيد",
      buttonLink: "./child-life",
      buttonTarget: "_self",
      description: "",
      textColor: "dark",
      bannerUrl: "/slide_img_2.jpg",
      bannerUrl_mob: "/slide_img_2_mob.jpg",
      srcType: "image",
    },
    {
      title: `ما هو\nتخصص حياة الطفل؟`,
      buttonText: "المزيد",
      buttonLink: "./child-life",
      buttonTarget: "_self",
      description: "",
      textColor: "light",
      bannerUrl: "/slide_img_3.jpg",
      bannerUrl_mob: "/slide_img_3_mob.jpg",
      srcType: "image",
    },
  ],
};
export const whoDataEN = {
  BANARS_DATA: [
    {
      title: "Who is \n Abdulrahman",
      buttonText: "More",
      buttonLink: "./about",
      buttonTarget: "_self",
      textColor: "light",
      description: "",
      bannerUrl: "/slide_img_1.jpg",
      bannerUrl_mob: "/slide_img_1_mob.jpg",
      srcType: "image",
    },
    {
      title:
        "Signing an agreement to launch the first #ChildLife program in the Kingdom of Saudi Arabia",
      buttonText: "More",
      buttonLink: "https://youtu.be/H1WqNYnCyRA",
      buttonTarget: "_blank",
      description:
        "Praise be to God, the first Child Life Program has been launched in the Kingdom of Saudi Arabia, in cooperation with the Sanad Charity Association and King Fahd Medical City. Child life specialists will start their duties in mid-March. We are happy with this achievement!",
      textColor: "light",
      bannerUrl: "./video_cover.mp4",
      srcType: "video",
    },
    {
      title: "Welcome to \n Child Life Awareness Month",
      buttonText: "More",
      buttonLink: "./child-life",
      buttonTarget: "_self",
      description: "",
      textColor: "dark",
      bannerUrl: "/slide_img_2.jpg",
      bannerUrl_mob: "/slide_img_2_mob.jpg",
      srcType: "image",
    },
    {
      title: "What is \n A child life major?",
      buttonText: "More",
      buttonLink: "./child-life",
      buttonTarget: "_self",
      description: "",
      textColor: "light",
      bannerUrl: "/slide_img_3.jpg",
      bannerUrl_mob: "/slide_img_3_mob.jpg",
      srcType: "image",
    },
  ],
};
