export const storyDataAR = {
  title: "قصة عبدالرحمن",
  description:
    "عبدالرحمن كان نهرا من الحب والعطاء اللا مشروط ، كان صديق المساكين والمحتاجين كان بشوشا متفائلا محبا للحياة ، فكان عند دخوله المنزل يبدأ بالسلام على العمالة ويحتفل بمناسبتهم ويسأل عن اطفالهم ، رغم صغر سنة إلا أنه علمنا دروسا في الوفاء والنبل . أسست هذه الواحة بعد رحيله ليستظل بها أطفالنا المرضى وأسرهم ، شفاهم الله . \n \nتأسست جمعية حياة الطفل/ واحة عبدالرحمن في عام 2022 بعد وفاة الشاب عبدالرحمن بن فهد بن ثنيان الثنيان رحمه الله في مقتبل عمره حيث أراد والديه تخليد ذکراه بعمل خيري يعود له بالثواب ويعم نفعه الأطفال المرضی شفاهم الله وأسرهم.. وقد اختير هذا التخصص لما فيه من تشابه لشخصية عبدالرحمن رحمه الله فمن يعرف عبدالرحمن يذهل بالبعد الإنساني الذي تتمحور عليه شخصية هذا الشاب ونظرته الإنسانية للآخرين وعطفه وحبه الخير منذ نعومة أظفاره حتی رحيله وحاجة المجتمع لمثل هذه الجمعية التي تهتم بنشر ثقافة حياة الطفل وتمکين أخصائيات حياة الطفل ببرامج التعليم والتدريب بالتعاون مع مستشفيات وجامعات محلية ودولية لتهيئة كوادر وطنية وضمان استدامة هذا التخصص الإنساني.",
};
export const storyDataEN = {
  title: "Abdulrahman's story",
  description:
    "Abd al-Rahman was a river of unconditional love and giving. He was a friend of the poor and needy. He was jovial, optimistic, and loved life. When he entered the house, he would greet the workers, celebrate their occasion, and ask about their children. Despite his young age, he taught us lessons in loyalty and nobility. This oasis was established after his departure to provide shelter for our sick children and their families, may God heal them. \n \n The Child Life Association / Abdul Rahman Oasis was established in 2022 after the death of the young Abdul Rahman bin Fahd bin Thunayan Al Thunayan, may God have mercy on him, in the prime of his life, as his parents wanted to immortalize his memory with a charitable work that would be rewarded for him, and the benefit of sick children, may God heal them and their families. Similarity to the personality of Abd al-Rahman, may God have mercy on him. Whoever knows Abd al-Rahman is amazed at the human dimension on which the personality of this young man is centered, his human view of others, his compassion and his love for goodness from his early childhood until his departure, and the community’s need for such an association that is concerned with spreading the culture of child life and empowering child life specialists with education and training programs in cooperation with hospitals and universities Local and international to prepare national cadres and ensure the sustainability of this human specialization.",
};
